
export const REQUEST_CITIES_PENDING = 'REQUEST_CITIES_PENDING';
export const REQUEST_CITIES_SUCCESS = 'REQUEST_CITIES_SUCCESS';
export const REQUEST_CITIES_FAILED = 'REQUEST_CITIES_FAILED';
export const RESET_RESULTS_ARRAY = 'RESET_RESULTS_ARRAY';


export const SET_CHOSEN_CITY = 'SET_CHOSEN_CITY';

export const REQUEST_ONE_DAY_FORCAST_PENDING = 'REQUEST_ONE_DAY_FORCAST_PENDING';
export const REQUEST_ONE_DAY_FORCAST_SUCCESS = 'EQUEST_ONE_DAY_FORCAST_SUCCESS';
export const REQUEST_ONE_DAY_FORCAST_FAILED = 'REQUEST_ONE_DAY_FORCAST_FAILED';

export const REQUEST_FIVE_DAY_FORCAST_PENDING = 'REQUEST_FIVE_DAY_FORCAST_PENDING';
export const REQUEST_FIVE_DAY_FORCAST_SUCCESS = 'REQUEST_FIVE_DAY_FORCAST_SUCCESS';
export const REQUEST_FIVE_DAY_FORCAST_FAILED = 'REQUEST_FIVE_DAY_FORCAST_FAILED';

export const ADD_TO_FAVORITES = 'ADD_TO_FAVORITES';
export const REMOVE_FROM_FAVORITES = 'REMOVE_FROM_FAVORITES';

export const SET_SEARCH_PAGE = 'SET_SEARCH_PAGE';
export const SET_FAVORITE_PAGE = 'SET_FAVORITE_PAGE';
export const SHOW_ONE_DAY_FORCAST = 'SHOW_ONE_DAY_FORCAST';
export const HIDE_ONE_DAY_FORCAST = 'HIDE_ONE_DAY_FORCAST';
export const SHOW_FIVE_DAY_FORCAST = 'SHOW_FIVE_DAY_FORCAST';
export const HIDE_FIVE_DAY_FORCAST = 'HIDE_FIVE_DAY_FORCAST';
